# Generated by Django 4.0.4 on 2022-07-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bluebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='pics')),
                ('issue_date', models.CharField(max_length=10)),
                ('expiry_date', models.CharField(max_length=10)),
                ('tax_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='license',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='pics')),
                ('blood_group', models.CharField(max_length=3)),
                ('dob', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
                ('issue_date', models.CharField(max_length=10)),
                ('expiry_date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='news_feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=1000)),
            ],
        ),
    ]
