# Generated by Django 4.0.4 on 2022-07-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluebook',
            name='bike_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
