# Generated by Django 4.0.4 on 2022-07-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_bluebook_bike_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluebook',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
