# Generated by Django 4.0.4 on 2022-07-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_bluebook_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationalid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bluebook',
            name='nationalid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='license.nationalid'),
        ),
        migrations.AddField(
            model_name='license',
            name='nationalid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='license.nationalid'),
        ),
    ]
