# Generated by Django 4.0.4 on 2022-07-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_alter_bluebook_nationalid_alter_license_nationalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalid',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
