# Generated by Django 4.0.4 on 2022-07-16 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_alter_bluebook_nationalid_alter_license_nationalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bluebook',
            name='nationalid',
        ),
        migrations.RemoveField(
            model_name='license',
            name='nationalid',
        ),
        migrations.RemoveField(
            model_name='nationalid',
            name='name',
        ),
        migrations.AddField(
            model_name='nationalid',
            name='bluebook_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='license.bluebook'),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='license_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='license.license'),
        ),
    ]
