# Generated by Django 4.0.4 on 2022-07-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_nationalid_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalid',
            name='name',
        ),
    ]
