# Generated by Django 4.0.4 on 2022-07-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0012_license_issue_nationalid_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bluebook_Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fine_Id', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='license.bluebook')),
            ],
        ),
        migrations.CreateModel(
            name='License_Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fine_Id', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='license.license')),
            ],
        ),
        migrations.DeleteModel(
            name='news_feed',
        ),
    ]
