# Generated by Django 4.0.6 on 2022-07-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0013_bluebook_fine_license_fine_delete_news_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluebook',
            name='address',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='capacity',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='chechis_no',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='color',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='contact_number',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='engine_no',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='engine_type',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='manufacture_date',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='no_of_cylinders',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='permit_for',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='power',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='use',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='v_category',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='bluebook',
            name='v_model',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='license',
            name='address',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='license',
            name='citizenship_no',
            field=models.CharField(max_length=200, null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AlterField(
            model_name='bluebook',
            name='book_number',
            field=models.CharField(max_length=100, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='bluebook',
            name='expiry_date',
            field=models.CharField(max_length=10, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='bluebook',
            name='issue_date',
            field=models.CharField(max_length=10, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='bluebook',
            name='name',
            field=models.CharField(max_length=100, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='bluebook',
            name='photo',
            field=models.ImageField(null='TRUE', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='bluebook',
            name='tax_status',
            field=models.CharField(max_length=10, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='license',
            name='blood_group',
            field=models.CharField(max_length=3, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='license',
            name='category',
            field=models.CharField(max_length=10, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='license',
            name='contact_number',
            field=models.CharField(max_length=20, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='license',
            name='dob',
            field=models.CharField(max_length=20, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiry_date',
            field=models.CharField(max_length=10, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='license',
            name='father_name',
            field=models.CharField(max_length=200, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='license',
            name='issue',
            field=models.CharField(default='not-issued', max_length=10, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='license',
            name='issue_date',
            field=models.CharField(max_length=10, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_number',
            field=models.CharField(max_length=20, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=200, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='license',
            name='photo',
            field=models.ImageField(null='TRUE', upload_to='pics'),
        ),
    ]
