# Generated by Django 4.0.6 on 2022-08-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0014_bluebook_address_bluebook_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='issue',
        ),
        migrations.AlterField(
            model_name='license_fine',
            name='amount',
            field=models.CharField(default='No charges', max_length=10),
        ),
    ]
