# Generated by Django 4.0.6 on 2022-08-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0015_remove_license_issue_alter_license_fine_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license_fine',
            old_name='name',
            new_name='nid',
        ),
    ]
