# Generated by Django 4.0.6 on 2022-11-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0018_alter_license_fine_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license_fine',
            name='amount',
            field=models.CharField(max_length=10, null='True'),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='bluebook_number',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='license.bluebook'),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='license_number',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='license.license'),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='name',
            field=models.CharField(max_length=20, null='True'),
        ),
    ]
