# Generated by Django 4.0.6 on 2023-04-25 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0020_alter_license_fine_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license_fine',
            name='Fine_Id',
        ),
    ]
