# Generated by Django 4.0.6 on 2023-04-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0022_remove_license_fine_national_id_license_fine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license_fine',
            old_name='nid',
            new_name='lid',
        ),
    ]
