# Generated by Django 4.0.6 on 2023-05-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0023_rename_nid_license_fine_lid'),
    ]

    operations = [
        migrations.AddField(
            model_name='license_fine',
            name='description',
            field=models.CharField(max_length=500, null='False'),
            preserve_default='False',
        ),
    ]
